apiVersion: v1
kind: Service
metadata:
  name: hadzy-service
spec:
  type: NodePort
  selector:
    app: seq
  ports:
    - name: seq-ui
      protocol: TCP
      targetPort: 80
      nodePort: 31291
    - name: seq-data-ingestion
      protocol: TCP
      targetPort: 5341
      nodePort: 31292