apiVersion: v1
kind: Service
metadata:
  name: hadzy-frontend-service
spec:
  type: NodePort
  selector:
    app: hadzy-frontend
  ports:
    - name: hadzy-frontend
      protocol: TCP
      port: 6000
      targetPort: 80
      nodePort: 32556