apiVersion: v1
kind: Service
metadata:
  name: seq-service
spec:
  type: NodePort
  selector:
    app: seq
  ports:
    - name: seq-ui
      protocol: TCP
      port: 6000
      targetPort: 80
      nodePort: 31291
    - name: seq-data-ingestion
      protocol: TCP
      port: 6001
      targetPort: 5341
      nodePort: 31292