apiVersion: v1
kind: Service
metadata:
  name: hadzy-core-service
spec:
  type: NodePort
  selector:
    app: hadzy-core
  ports:
    - name: hadzy-core
      protocol: TCP
      port: 6000
      targetPort: 80
      nodePort: 33000