apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - name: jenkins-ui
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32000
    - name: slave
      protocol: TCP
      port: 50000
    - name: http
      port: 80
      targetPort: 8080